### ISSUE TITLE
missing main parameter in bower. 

### ISSUE THREAD

**Issue by frozonfreak** [ianmurrays/ngColorThief#4]
Missing "main" parameter in bower.json. 

Causes failure to append files to html on grunting.. 

Works fine after adding "main": "angular-colorthief.min.js", to bower.json

**Comment by ianmurrays** [comment]
Doesn't #2 take care of this?

**Comment by frozonfreak** [comment]
Ah yes, its the same. 

Think i got some older revision when installed via bower.. Ill check that
