### ISSUE TITLE
add new version with bower main path to bower

### ISSUE THREAD

**Issue by philhudson91** [ianmurrays/ngColorThief#6]
The current bower.json file on bower is outdated :(

**Comment by ianmurrays** [comment]
Outdated how? What do you mean?

**Comment by philhudson91** [comment]
Current version on bower 0.1.0 is missing the `main` path to the main .js file.

If you download the zip from here the path is missing :)

https://www.versioneye.com/javascript/ianmurrays:angular-colorthief/0.1.0

**Comment by ianmurrays** [comment]
Done ;)

**Comment by philhudson91** [comment]
legend :D have an awesome wonderful cat filled adventure day!

**Comment by ianmurrays** [comment]
😸
