### ISSUE TITLE
$colorThiefProvider needs to be used in the config not $colorThief

### ISSUE THREAD

**Issue by bmwertman** [ianmurrays/ngColorThief#7]
Hey great wrapper! Just found a minor thing and wanted to let you know. The docs show passing `$colorThiefProvider` to the config for setting globals, which is correct, but then the methods are being called on `$colorThief`. That part doesn't work. Those methods are only available on `$colorThiefProvider`.

**Comment by ianmurrays** [comment]
Thanks! 👍
